### PR TITLE
Upgrade to React Navigation 6.x

### LINKED ISSUE #43: Upgrade to React Navigation 6.0
React Navigation 6.0 is coming! But don't worry it's still in beta [On the way to React Navigation 6.0](https://reactnavigation.org/blog/2021/03/12/react-navigation-6.0-next/)

They also wrote a really clean upgrading post that will help us migrating [Upgrading from 5.x](https://reactnavigation.org/docs/6.x/upgrading-from-5.x)

Interesting part I noticed is changes on the **Linking** config. For now we don't have linking config on the bindings, I created my own on my app but never backport it here because some weird case that lead to be to tied with the app in the end.
With changes on V6 I think it will be doable, I want to test it!

This upgrade will wait Rescript Migration #42 I think.

### PR DESCRIPTION
**Pull request by vknez**
I followed https://reactnavigation.org/docs/upgrading-from-5.x, but there might be things that are not covered. However, this is enough for us to use React Navigation 6 in a not-so-small React Native (ReScript + TypeScript) app.

I upgraded package version from 5.2.0 to 6.0.0.

Closes #43

### CODE REVIEW

**Comment by Freddy03h** [comment]
Ok! I've got time to test it, and it work well, I migrated easily thank's to your work ^^
The only missing things I noted are `header` and `headerShown` params in `BottomTabs` `screenOptions`.

I think `header` will need a bigger refactor because `Header.t` is, for now, to tied to `Stack`, maybe if we plan to update the binding to use the new `@react-navigation/elements` package it can be doable. But not mandatory for now.

However it's easy to add `~headerShown: bool=?` to `options` in `BottomTabs` and I think it's mandatory for anyone using nested navigators.

**Comment by vknez** [comment]
Thanks @Freddy03h. The fix will follow shortly.

**Review by Freddy03h — APPROVED** [review]

**Comment by Freddy03h** [comment]
@MoOx do you want to test it too before we merge ?

**Comment by MoOx** [comment]
No time atm. Let's merge this, I trust you :)

**Review by MoOx — APPROVED** [review]

**Pull request merged**
